#!/usr/bin/env python3
"""Generate seed.sql by extracting all content from index.tsx."""
import re, json

with open('/home/user/webapp/src/index.tsx', 'r', encoding='utf-8') as f:
    html = f.read()

def esc(s):
    """Escape single quotes for SQL."""
    return s.replace("'", "''")

def extract_pairs(section_start, section_end):
    """Extract data-ru/data-am pairs between two markers in html."""
    start_idx = html.find(section_start)
    if start_idx == -1:
        return []
    end_idx = html.find(section_end, start_idx + len(section_start))
    if end_idx == -1:
        end_idx = len(html)
    chunk = html[start_idx:end_idx]
    pattern = r'data-ru="([^"]*?)"\s+data-am="([^"]*?)"'
    return re.findall(pattern, chunk)

# ============================
# Build sections content as JSON
# ============================
sections = {}

# Helper: extract a section's texts as list of {ru, am} dicts
def add_section(key, name, start_marker, end_marker):
    pairs = extract_pairs(start_marker, end_marker)
    items = []
    for ru, am in pairs:
        items.append({"ru": ru, "am": am})
    sections[key] = {"name": name, "items": items}

# Map sections to their HTML comments/markers
add_section("nav", "Навигация (шапка)", "<!-- ===== HEADER =====", "<!-- ===== HERO =====")
add_section("hero", "Hero секция", "<!-- ===== HERO =====", "<!-- ===== TICKER =====")
add_section("wb_banner", "WB Баннер", "<!-- ===== WB BANNER =====", "<!-- ===== STATS BAR =====")
add_section("stats_bar", "Статистика", "<!-- ===== STATS BAR =====", "<!-- ===== ABOUT =====")
add_section("about", "О компании", "<!-- ===== ABOUT =====", "<!-- ===== SERVICES =====")
add_section("services", "Наши услуги", "<!-- ===== SERVICES =====", "<!-- ===== BUYOUT DETAIL =====")
add_section("buyout_detail", "Детали выкупа", "<!-- ===== BUYOUT DETAIL =====", "<!-- ===== WHY BUYOUTS")
add_section("why_buyouts", "Почему выкупы работают", "<!-- ===== WHY BUYOUTS", "<!-- ===== WB OFFICIAL =====")
add_section("wb_official", "WB Official", "<!-- ===== WB OFFICIAL =====", "<!-- ===== CALCULATOR =====")
add_section("calculator", "Калькулятор (заголовки)", "<!-- ===== CALCULATOR =====", "<!-- ===== PROCESS =====")
add_section("process", "Как мы работаем", "<!-- ===== PROCESS =====", "<!-- ===== WAREHOUSE =====")
add_section("warehouse", "Наш склад", "<!-- ===== WAREHOUSE =====", "<!-- ===== GUARANTEE =====")
add_section("guarantee", "Гарантия безопасности", "<!-- ===== GUARANTEE =====", "<!-- ===== COMPARISON =====")
add_section("comparison", "Сравнение", "<!-- ===== COMPARISON =====", "<!-- ===== IMPORTANT NOTES =====")
add_section("important", "Важно знать", "<!-- ===== IMPORTANT NOTES =====", "<!-- ===== FAQ =====")
add_section("faq", "Частые вопросы (FAQ)", "<!-- ===== FAQ =====", "<!-- ===== CONTACT FORM =====")
add_section("contact", "Контактная форма", "<!-- ===== CONTACT FORM =====", "<!-- ===== FOOTER =====")
add_section("footer", "Подвал сайта", "<!-- ===== FOOTER =====", "<!-- FLOATING TG BUTTON")
add_section("popup", "Popup (5 сек)", "<!-- ===== POPUP", "</script>")

# ============================
# Generate SQL
# ============================
lines = []
lines.append("-- Auto-generated seed data from index.tsx")
lines.append("-- Generated by generate_seed.py")
lines.append("")

# Default admin user (password will be set on first login)
lines.append("-- Default admin: username=admin, password=gototop2026")
lines.append("-- Password hash is SHA-256 of 'gototop2026' (will be replaced with proper bcrypt at runtime)")
lines.append("INSERT OR IGNORE INTO users (username, password_hash, role, display_name) VALUES")
lines.append("  ('admin', 'SETUP_REQUIRED', 'admin', 'Администратор');")
lines.append("")

# Site content sections
lines.append("-- ===== SITE CONTENT SECTIONS =====")
sort = 0
for key, data in sections.items():
    sort += 1
    content_json = json.dumps(data["items"], ensure_ascii=False)
    lines.append(f"INSERT OR REPLACE INTO site_content (section_key, section_name, content_json, sort_order) VALUES")
    lines.append(f"  ('{esc(key)}', '{esc(data['name'])}', '{esc(content_json)}', {sort});")
lines.append("")

# Calculator tabs
lines.append("-- ===== CALCULATOR TABS =====")
tabs = [
    ("buyouts", "Выкупы", "Գնումներ", 1),
    ("reviews", "Отзывы", "Կարծիքներ", 2),
    ("photo", "Фотосъёмка", "Լdelays", 3),
    ("ff", "ФФ", " Delays", 4),
    ("logistics", "Логистика", "Delays", 5),
    ("other", "Прочие услуги", "Delays", 6),
]
# Re-extract from HTML
tab_pattern = r'showCalcTab\(\'(\w+)\',this\)"\s+data-ru="([^"]*?)"\s+data-am="([^"]*?)"'
tab_matches = re.findall(tab_pattern, html)
if tab_matches:
    tabs = [(key, ru, am, i+1) for i, (key, ru, am) in enumerate(tab_matches)]

for key, ru, am, sort in tabs:
    lines.append(f"INSERT OR IGNORE INTO calculator_tabs (tab_key, name_ru, name_am, sort_order) VALUES")
    lines.append(f"  ('{esc(key)}', '{esc(ru)}', '{esc(am)}', {sort});")
lines.append("")

# Calculator services from HTML
lines.append("-- ===== CALCULATOR SERVICES =====")

# Extract services per tab from calc-group sections
calc_section = html[html.find('<!-- ===== ВЫКУПЫ ====='):html.find('</div>\n    <div class="calc-total">')]
tab_blocks = re.split(r'<!-- =====.*?===== -->', calc_section)

# Parse each calc-group
group_pattern = r'id="cg-(\w+)"'
groups = re.findall(group_pattern, html)

for group_key in groups:
    start = html.find(f'id="cg-{group_key}"')
    end = html.find('</div>\n\n', start)
    if end == -1:
        end = html.find('</div>\n    <div class="calc-total">', start)
    block = html[start:end]
    
    # Find tab_id
    tab_idx = next((i+1 for i, (k, _, _, _) in enumerate(tabs) if k == group_key), 0)
    
    # Extract rows
    row_pattern = r'data-price="([^"]*?)".*?calc-label"[^>]*data-ru="([^"]*?)"\s+data-am="([^"]*?)"'
    rows = re.findall(row_pattern, block, re.DOTALL)
    
    for sort_i, (price, ru, am) in enumerate(rows, 1):
        # Special: buyout row with tiered pricing
        if price == 'buyout':
            tiers = json.dumps([
                {"min":1,"max":20,"price":2000},
                {"min":21,"max":40,"price":1700},
                {"min":41,"max":60,"price":1500},
                {"min":61,"max":999,"price":1250}
            ])
            # Get tier descriptions
            tier_desc_ru = "1-20 шт → ֏2 000 | 21-40 шт → ֏1 700 | 41-60 шт → ֏1 500 | 60+ шт → ֏1 250"
            tier_desc_am = "1-20 հdelays → ֏2 000 | 21-40 հdelays → ֏1 700 | 41-60 հdelays → ֏1 500 | 60+ հdelays → ֏1 250"
            
            # Re-extract from HTML
            tier_match = re.search(r'buyout-tier-info.*?<span[^>]*data-ru="([^"]*?)"\s+data-am="([^"]*?)"', html, re.DOTALL)
            if tier_match:
                tier_desc_ru = tier_match.group(1)
                tier_desc_am = tier_match.group(2)
            
            lines.append(f"INSERT OR IGNORE INTO calculator_services (tab_id, name_ru, name_am, price, price_type, price_tiers_json, tier_desc_ru, tier_desc_am, sort_order) VALUES")
            lines.append(f"  ({tab_idx}, '{esc(ru)}', '{esc(am)}', 2000, 'tiered', '{esc(tiers)}', '{esc(tier_desc_ru)}', '{esc(tier_desc_am)}', {sort_i});")
        else:
            lines.append(f"INSERT OR IGNORE INTO calculator_services (tab_id, name_ru, name_am, price, price_type, sort_order) VALUES")
            lines.append(f"  ({tab_idx}, '{esc(ru)}', '{esc(am)}', {price}, 'fixed', {sort_i});")
lines.append("")

# Telegram messages
lines.append("-- ===== TELEGRAM MESSAGES =====")

# Extract all telegram buttons from HTML
tg_buttons = [
    ("hero_cta", "Написать в Telegram", "Գرel Telegram-ov", "https://t.me/goo_to_top",
     "Здравствуйте! Хочу узнать о продвижении товара на Wildberries.",
     "Ողdelays! Delays Wildberries.",
     "Кнопка Hero"),
]
# Better: extract programmatically
# Find all <a href="https://t.me/..." with data-ru/data-am on button labels
tg_btn_pattern = r'<a\s+href="(https://t\.me/[^"]+)"[^>]*>.*?<span\s+data-ru="([^"]*?)"\s+data-am="([^"]*?)"'
tg_btns = re.findall(tg_btn_pattern, html, re.DOTALL)

used_keys = set()
tg_messages = []
for url, label_ru, label_am in tg_btns:
    # Generate key from label
    key = re.sub(r'[^a-z0-9]+', '_', label_ru.lower()[:40].strip())
    key = re.sub(r'_+', '_', key).strip('_')
    if key in used_keys:
        key += f"_{len(used_keys)}"
    used_keys.add(key)
    
    msg_ru = f"Здравствуйте! Пишу с сайта Go to Top. Интересует: {label_ru}"
    msg_am = f"Ողdelays! Go to Top: {label_am}"
    
    tg_messages.append((key, label_ru, label_am, url, msg_ru, msg_am, f"Кнопка: {label_ru}"))

for key, label_ru, label_am, url, msg_ru, msg_am, desc in tg_messages:
    lines.append(f"INSERT OR IGNORE INTO telegram_messages (button_key, button_label_ru, button_label_am, telegram_url, message_template_ru, message_template_am, description, sort_order) VALUES")
    lines.append(f"  ('{esc(key)}', '{esc(label_ru)}', '{esc(label_am)}', '{esc(url)}', '{esc(msg_ru)}', '{esc(msg_am)}', '{esc(desc)}', 0);")

# Add special messages for forms
lines.append("")
lines.append("-- Special form messages")
lines.append("INSERT OR IGNORE INTO telegram_messages (button_key, button_label_ru, button_label_am, telegram_url, message_template_ru, message_template_am, description) VALUES")
lines.append("""  ('calc_order_msg', 'Заказать в Telegram', 'Պатvirel Telegram-ov', 'https://t.me/goo_to_top',
   'Здравствуйте! Хочу заказать:\\n{items}\\n\\nИтого: ֏{total}',
   'Ողdelays! Delays:\\n{items}\\n\\nDelays: ֏{total}',
   'Шаблон сообщения калькулятора');""")
lines.append("INSERT OR IGNORE INTO telegram_messages (button_key, button_label_ru, button_label_am, telegram_url, message_template_ru, message_template_am, description) VALUES")
lines.append("""  ('popup_form_msg', 'Получить расchёт в Telegram', 'Stanaldelays Telegram-ov', 'https://t.me/suport_admin_2',
   'Заявка с сайта Go to Top:\\n\\nВыкупов: {buyouts}\\nОтзывов: {reviews}\\nКонтакт: {contact}',
   'Delays Go to Top:\\n\\nDelays: {buyouts}\\nDelays: {reviews}\\nDelays: {contact}',
   'Шаблон popup формы');""")
lines.append("INSERT OR IGNORE INTO telegram_messages (button_key, button_label_ru, button_label_am, telegram_url, message_template_ru, message_template_am, description) VALUES")
lines.append("""  ('contact_form_msg', 'Отправить заявку', 'Delays delays', 'https://t.me/suport_admin_2',
   'Здравствуйте! Заявка с сайта Go to Top:\\n\\nИмя: {name}\\nКонтакт: {contact}\\nТовар: {product}\\nУслуга: {service}\\nКомmentarий: {message}',
   'Delays Go to Top:\\n\\nDelays: {name}\\nDelays: {contact}\\nDelays: {product}\\nDelays: {service}\\nDelays: {message}',
   'Шаблон контактной формы');""")

lines.append("")
lines.append("-- ===== CUSTOM SCRIPTS (empty by default) =====")
lines.append("-- Admin can add analytics, pixels etc. via admin panel")
lines.append("")

sql = "\n".join(lines)

with open('/home/user/webapp/seed.sql', 'w', encoding='utf-8') as f:
    f.write(sql)

print(f"Generated seed.sql with {len(sections)} content sections, {len(tabs)} calc tabs, {len(tg_messages)} telegram buttons")
print(f"Total text pairs per section:")
for key, data in sections.items():
    print(f"  {key}: {len(data['items'])} texts")
